1point1kb: false
limitvert: true
ylimit: 1.2
horizontal: 0.46
vertical: 0.36
inherith: true
inheritv: false
ihstrh: 1.0
ihstrv: 1.0
groundh: 1.1
groundv: 1.0
sprinth: 1.2
sprintv: 1.0
bowh: 1.2
bowv: 1.0
rodh: 1.2
rodv: 1.0
nodamageticks: 20
combo: false
comboticks: 10
combovelocity: -0.05
comboheight: 2.5
stopsprint: true
slowdown: 0.6
potionfall: 0.05
potionmultiplier: 0.5
potionoffset: -10.0
